# Generated by Django 5.1 on 2025-05-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_gideon', '0002_alter_person_forename_alter_versionperson_forename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionperson',
            name='version_tag',
        ),
    ]
