# Generated by Django 5.1 on 2025-05-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_gideon', '0004_alter_person_options_alter_place_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bornin',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='diedin',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='personcorrigendum',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='personpublication',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='personquote',
            options={'ordering': ['id']},
        ),
    ]
